ERROR:pygls.protocol:Failed to handle request 9 textDocument/hover HoverParams(text_document=TextDocumentIdentifier(uri='file:///home/haru/esquizoDB/scripts/tp1_3.2.py'), position=231:0, work_done_token=None)
Traceback (most recent call last):
  File "/home/haru/.vscode-oss/extensions/ms-python.python-2023.6.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/haru/.vscode-oss/extensions/ms-python.python-2023.6.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request
    self._send_response(msg_id, handler(params))
  File "/home/haru/.vscode-oss/extensions/ms-python.python-2023.6.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover
    jedi_script.help(
  File "/home/haru/.vscode-oss/extensions/ms-python.python-2023.6.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (1) is not in a valid range (0-0) for line 232 ('\n').
[Error - 7:22:04â€¯PM] Request textDocument/hover failed.
  Message: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 232 ('\n').
  Code: -32602 
{'traceback': ['  File "/home/haru/.vscode-oss/extensions/ms-python.python-2023.6.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 337, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/haru/.vscode-oss/extensions/ms-python.python-2023.6.0-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 261, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "/home/haru/.vscode-oss/extensions/ms-python.python-2023.6.0-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 378, in hover\n    jedi_script.help(\n', '  File "/home/haru/.vscode-oss/extensions/ms-python.python-2023.6.0-universal/pythonFiles/lib/jedilsp/jedi/api/helpers.py", line 484, in wrapper\n    raise ValueError(\'`column` parameter (%d) is not in a valid range \'\n']}
WARNING:pygls.protocol:Cancel notification for unknown message id "12"
WARNING:pygls.protocol:Cancel notification for unknown message id "16"
WARNING:pygls.protocol:Cancel notification for unknown message id "27"
WARNING:pygls.protocol:Cancel notification for unknown message id "42"
WARNING:pygls.protocol:Cancel notification for unknown message id "45"
WARNING:pygls.protocol:Cancel notification for unknown message id "70"
WARNING:pygls.protocol:Cancel notification for unknown message id "92"
WARNING:pygls.protocol:Cancel notification for unknown message id "124"
WARNING:pygls.protocol:Cancel notification for unknown message id "197"
WARNING:pygls.protocol:Cancel notification for unknown message id "267"
WARNING:pygls.protocol:Cancel notification for unknown message id "274"
WARNING:pygls.protocol:Cancel notification for unknown message id "287"
